version: "3.2"
services:
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=room4_test_db
    ports:
      - "3307:3306"
    container_name: room4-db
  nodejs:
    build:
      context: .
    image: room4/room4-nodejs-test
    environment:
      - MYSQL_HOST=room4-db
      - MYSQL_USER=root
      - MYSQL_PASS=
      - MYSQL_DB=room4_test_db
    links:
      - mysql:mysql
    networks:
      - backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - mysql
    container_name: room4-nodejs-test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "5001:80"
    environment:
      - PMA_HOST=room4-db
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: room4-phpmyadmin
networks:
  backend:
